name: Push to ECR
on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: us-west-2

      - name: Build and push Docker image
        run: |
          docker build -t cypress-reg .
          docker tag cypress-reg:latest 772928143835.dkr.ecr.us-west-2.amazonaws.com/cypress-reg:latest
          docker push 772928143835.dkr.ecr.us-west-2.amazonaws.com/cypress-reg:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
